---

name: Molecule
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    paths-ignore:
      - '**/*.md'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5

      - name: Set up Python 3.
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint ansible

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - almalinux9
          - rockylinux9
          - debian12
          - ubuntu2204
          - ubuntu2404

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5

      - name: Set up Python 3.
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker requests

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
